### ISSUE TITLE
Operator should error out when credentialsSecret is missing

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/airflow-operator#292]
### Affected version

0.0.0-dev

### Current and expected behavior

When `spec.clusterConfig.credentialsSecret` points to a non-existent Secret the operator **should** error out, currently it just does not apply a Job manifests, no error is shown.
At least the following code is affected: https://github.com/stackabletech/airflow-operator/blob/e767be7888e910d7cf90e2d49e1345720b8b8446/rust/operator-binary/src/airflow_db_controller.rs#L158

### Additional context

```
---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow2
spec:
  image:
    productVersion: 2.6.1
    stackableVersion: 0.0.0-dev
  clusterConfig:
    executor: CeleryExecutor
    loadExamples: false
    exposeConfig: false
    credentialsSecret: simple-airflow-credentials # <<< Does not exist
    dagsGitSync:
      - repo: https://github.com/stackabletech/XXX
        branch: "main"
        gitFolder: "airflow_dags"
        depth: 10
        wait: 20
        gitSyncConf:
          --rev: HEAD
  webservers:
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 2
  schedulers:
    roleGroups:
      default:
        replicas: 1
```

### Would you like to work on fixing this bug?

None
