### ISSUE TITLE
Airflow service-account cannot create/get sparkapplications

### ISSUE THREAD

**Issue by vasili439** [stackabletech/airflow-operator#419]
### Affected Stackable version

24.3.0

### Affected Apache Airflow version

2.6.3

### Current and expected behavior

Current behavior: when I create airflow job I see the following error:
`[2024-04-05, 13:05:30 UTC] {rest.py:231} DEBUG - response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"sparkapplications.spark.stackable.tech is forbidden: User \"system:serviceaccount:stackable-stack:airflow-serviceaccount\" cannot create resource \"sparkapplications\" in API group \"spark.stackable.tech\" in the namespace \"stackable-stack\"","reason":"Forbidden","details":{"group":"spark.stackable.tech","kind":"sparkapplications"},"code":403}
[2024-04-05, 13:05:30 UTC] {taskinstance.py:1824} ERROR - Task failed with exception`

### Possible solution

Patch airflow service-account with:
```
   - verbs:
       - create
       - delete
       - get
     apiGroups:
       - spark.stackable.tech
     resources:
       - sparkapplications
```

### Additional context

If my observation make sense please include it to the upcoming release.

### Would you like to work on fixing this bug?

yes
