### ISSUE TITLE
gitCredentialsSecret doesn't follow RFC 1123 specification

### ISSUE THREAD

**Issue by petardjurkovic** [stackabletech/airflow-operator#486]
### Affected Stackable version

24.7.0

### Affected Apache Airflow version

2.9.2

### Current and expected behavior

**When gitSync is enabled** 
```
dagsGitSync:
      - repo: https://gitlink/airflow-dags.git
        branch: release/test
        gitFolder: ./dags
        credentialsSecret: git-credentials
      - repo: https://gitlink/airflow-plugins.git
        branch: release/test
        gitFolder: ./plugins
        credentialsSecret: git-credentials
```
`---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: Opaque
stringData:
  user: someuser
  password: somepassword`
**down errors preventing airflow-webserver to be created:**
`create Pod airflow-webserver-default-1 in StatefulSet airflow-webserver-default failed error: Pod "airflow-webserver-default-1" is invalid: [spec.containers[2].env[2].valueFrom.secretKeyRef.name: Invalid value: "gitCredentialsSecret": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.containers[2].env[3].valueFrom.secretKeyRef.name: Invalid value: "gitCredentialsSecret": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]`

### Would you like to work on fixing this bug?

maybe
