### ISSUE TITLE
Add support for named worker queues

### ISSUE THREAD

**Issue by garymosco** [stackabletech/airflow-operator#497]
We would like to use multiple workers which work can be sent to using the worker queue functionality in airflow.

In the image args in the yaml we can see the "airflow celery worker" command being defined but would like to pass in a queue name i.e. creating a worker with the "airflow celery worker -q <queue_name>" command if a name is specified.

**Comment by dervoeti** [comment]
Hi,
this should be possible by overriding the default queue for each worker, like this:
```
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  ...
  celeryExecutors:
    roleGroups:
      default:
        envOverrides:
          AIRFLOW__OPERATORS__DEFAULT_QUEUE: myqueue
        replicas: 1
      otherworkers:
        envOverrides:
          AIRFLOW__OPERATORS__DEFAULT_QUEUE: myotherqueue
        replicas: 1
...
```

Does that solve your problem?
