### ISSUE TITLE
Git sync doesn't clone repo on right location

### ISSUE THREAD

**Issue by petardjurkovic** [stackabletech/airflow-operator#499]
### Affected Stackable version

24.7.0

### Affected Apache Airflow version

nightly

### Current and expected behavior

Gitsync clone the repo but not on expected location specified in gitFolder defined in deployment file.
```yaml
    dagsGitSync:
      - repo: https://git_url/airflow-dags.git
        branch: release/test
        gitFolder: ./dags
        credentialsSecret: git-credentials
``` 

### Would you like to work on fixing this bug?

None
