### ISSUE TITLE
Airflow 3.x: replace hard-coded JWT secret key with one read from a secret (or auto-generated)

### ISSUE THREAD

**Issue by adwk67** [stackabletech/airflow-operator#639]
The experimental support for Airflow 3.x includes temporary use of a hard-coded constant for the [JWT secret](https://airflow.apache.org/docs/apache-airflow/3.0.0/configurations-ref.html#jwt-secret). This should be replaced with a value from a secret, which can be auto-generated if defined as such in the custom resource.

Further to https://github.com/stackabletech/decisions/issues/59, this will be done by creating the key in a named secret (if it does not already exist).

#### Previously

We can use the existing credentialsSecret by adding a JWT key:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: test-airflow-credentials
type: Opaque
stringData:
  adminUser.username: airflow
  ...
  jwt.key: thisISaJwTSECRET_1234
  ...
```

Two issues, discovered during the initial 3.x PR, should be investigated:

- ~operator restart results in airflow cluster restart (that should not be happening)~
- ~the session / token in the UI is still valid (no obvious explanation for this)~
