### ISSUE TITLE
Improvement: Make task handler configurable in airflow crd's

### ISSUE THREAD

**Issue by Maleware** [stackabletech/airflow-operator#650]
As of now we addressed an [issue](https://github.com/stackabletech/airflow-operator/issues/646) of airflow logging with [this](https://github.com/stackabletech/airflow-operator/pull/649) PR.

However this is not the best possible solution. Ideally we'd like to have a situation like
```
          logging:
            containers:
              airflow:
                console:
                  level: INFO
                file:
                  level: INFO
                task:
                  level: INFO
                loggers:
                  ROOT:
                    level: INFO
```
in airflow CRD's, setting the handlers log level.

[This](https://github.com/stackabletech/airflow-operator/blob/main/rust/operator-binary/src/product_logging.rs#L118) comment is a working solution which needs to be implemented comparable to `file` and `console`.
